### ISSUE TITLE
FIXMES

### ISSUE THREAD

**Issue by IsaKiko** [GovHackMelbourne/CrimeDataProject#10]
1. The time picker does not currently change the time of day (should be an easy fix I ran out of time this morning)
2.  The sizing and positioning of the buttons on mobile. 
3. Adding a return to start button at the end of the tell me more section.
4. Probably others that you will find
5. Tweet button's got security issues
6. Fb button does nothing so far ;)

**Comment by andrejvidic** [comment]
Thanks @IsaKiko for putting this up. I might just close this issue as we should create separate issues as it provides better progress visibility, task splitting ability and notes organisation.

Could you please recreate these as seperate issues? (I have done the first, will leave the rest to you)

If you cannot get to it by this evening I will get it done :-)

**Comment by IsaKiko** [comment]
Sure thing - will do it later!
